### ISSUE TITLE
Make initial config lighter / easier

### ISSUE THREAD

**Issue by Dinopony** [Hawkrex/RandstalkerGUI#3]
Currently, the initial config asks you to fill those params :

![image](https://user-images.githubusercontent.com/6233833/184706875-9d70051c-7ac8-4761-a088-745c29985c30.png)

Five entries seems a bit tedious to fill, especially when the common use case is very simple :

1. User downloads Randstalker, extracts it to a folder
2. User downloads GUI, extracts it to a folder
3. User launches GUI

From there, the user only needs to specify 3 things for the app to work:
- the location of the randstalker directory
- the input rom location
- the output roms folder (pre-filled with "./seeds/" so that seeds are generated inside a GUI subfolder)

### Preset folder?

People won't fiddle manually with preset files (or very rarely), so they don't need to know where they are stored, as long as it works.
Since default presets needs to be included and we don't want to put that kind of responsability on the GUI, we'll just use a subfolder of randstalker called "presets".
Either we leave the option to change this, in which case we need some kind of auto-filled entry (which concatenates "/presets/" to the provided randstalker folder), **OR** we just remove this option completely and people will learn that their presets are in a well-named randstalker subfolder.

### Personal settings folder?

Personal settings are just a way to store the most common personal settings in a convenient file so that people don't have to change those everytime. I think it needs to be handled as a file, rather than a folder of various personal settings. But more importantly, it must not matter how it is stored for the player, but it needs to be easily accessed from the front page to switch quickly on-the-go.

**Comment by Hawkrex** [comment]
I would go further and only ask the root "Randstalker" folder for the initial config and automatically populate with default values the precision fields.

I prefer the user to have the choice to fully customize their options, but initialize them with default ones.

For the personal settings folder, I think we should discuss it with the community on Discord.


**I'll make a detailed plan on how changes should be implemented when we will discuss about the last point**
